const-correctness (#318)
* Many const-correctness improvements.

* Port over new y_ini code.

* Correctly write empty tags, parents, and comments.

* Escape semi-colons in writes.

* Accidentally broke reading no tags.

* Handle NULL in string hashes.

* Ignore `const &var` warnings.

* Ensure line identification tests work in all states.

* Forward-compatible code.

* [y_master] fixed warnings 214 & 239

YSI_Core\y_master\y_master_once.inc(524) : warning 214: possibly a "const" array argument was intended: "library"
YSI_Core\y_master\y_master_once.inc(555) : warning 214: possibly a "const" array argument was intended: "library"
YSI_Core\y_master\y_master__impl.inc(292) : warning 239: literal array/string passed to a non-const parameter
YSI_Core\y_master\y_master__impl.inc(682) : warning 239: literal array/string passed to a non-const parameter

* [y_area] fixed warning 214

YSI_Visual\y_areas\y_areas_entry.inc(1991) : warning 214: possibly a "const" array argument was intended: "areas"
YSI_Visual\y_areas\y_areas_entry.inc(2080) : warning 214: possibly a "const" array argument was intended: "bounds"
YSI_Visual\y_areas\y_areas_entry.inc(2115) : warning 214: possibly a "const" array argument was intended: "bounds"
YSI_Visual\y_areas\y_areas_entry.inc(2246) : warning 214: possibly a "const" array argument was intended: "bounds"

* [y_languages] fixed warning 214

YSI_Players\y_languages\y_languages_entry.inc(265) : warning 214: possibly a "const" array argument was intended: "identifier"
YSI_Players\y_languages\y_languages_entry.inc(397) : warning 214: possibly a "const" array argument was intended: "code"

* [y_classes] fixed warning 214

YSI_Visual\y_classes\y_classes_multiclass.inc(539) : warning 214: possibly a "const" array argument was intended: "w"

* [y_playerarray] fixed warning 214

YSI_Data\y_playerarray\y_playerarray_entry.inc(141) : warning 214: possibly a "const" array argument was intended: "data"

* [y_text] fixed warning 214

YSI_Players\y_text\y_text_render.inc(149) : warning 214: possibly a "const" array argument was intended: "lst"
YSI_Players\y_text\y_text_render.inc(161) : warning 214: possibly a "const" array argument was intended: "label"
YSI_Players\y_text\y_text_render.inc(161) : warning 214: possibly a "const" array argument was intended: "style"
YSI_Players\y_text\y_text_render.inc(818) : warning 214: possibly a "const" array argument was intended: "out"
YSI_Players\y_text\y_text_render.inc(828) : warning 214: possibly a "const" array argument was intended: "out"
YSI_Players\y_text\y_text_render.inc(833) : warning 214: possibly a "const" array argument was intended: "out"

* [y_text] fixed warning 214, 203 & 1052

YSI_Players\y_text\y_text_impl.inc(299) : warning 214: possibly a "const" array argument was intended: "buffer"
YSI_Players\y_text\y_text_impl.inc(570) : warning 203: symbol is never used: "str"
YSI_Players\y_text\y_text_impl.inc(570) : warning 203: symbol is never used: "file"
YSI_Players\y_text\y_text_impl.inc(592) : warning 203: symbol is never used: "name"
YSI_Players\y_text\y_text_impl.inc(936) : warning 214: possibly a "const" array argument was intended: "ident"
YSI_Players\y_text\y_text_impl.inc(1052) : warning 239: literal array/string passed to a non-const parameter

* [y_svar] fixed warning 239

YSI_Storage\y_svar\y_svar_ini.inc(162) : warning 239: literal array/string passed to a non-const parameter
YSI_Storage\y_svar\y_svar_ini.inc(179) : warning 239: literal array/string passed to a non-const parameter

* [y_php] fixed warning 214

YSI_Storage\y_php\y_php_entry.inc(288) : warning 214: possibly a "const" array argument was intended: "str"
YSI_Storage\y_php\y_php_entry.inc(293) : warning 214: possibly a "const" array argument was intended: "str"
YSI_Storage\y_php\y_php_entry.inc(298) : warning 214: possibly a "const" array argument was intended: "str"

* [y_unique] fixed error 017

YSI_Coding\y_unique\y_unique_entry.inc(152) : error 017: undefined symbol "YSI_gLockData"
YSI_Coding\y_unique\y_unique_entry.inc(152) : warning 215: expression has no effect
YSI_Coding\y_unique\y_unique_entry.inc(152) : error 001: expected token: ";", but found "]"
YSI_Coding\y_unique\y_unique_entry.inc(152) : error 029: invalid expression, assumed zero
YSI_Coding\y_unique\y_unique_entry.inc(152) : fatal error 107: too many error messages on one line

* [y_properties] fixed warnings/errors

YSI_Visual\y_properties\y_properties_entry.inc(104) : warning 201: redefinition of constant/macro (symbol "WEAPON_ARMOUR")
YSI_Visual\y_properties\y_properties_entry.inc(145) : error 017: undefined symbol "PLAYER_BIT_ARRAY"
YSI_Visual\y_properties\y_properties_entry.inc(174) : error 017: undefined symbol "MAX_CHECKPOINTS"
YSI_Visual\y_properties\y_properties_entry.inc(326) : error 017: undefined symbol "MAX_CHECKPOINTS"
YSI_Visual\y_properties\y_properties_entry.inc(715) : error 010: invalid function or declaration
YSI_Visual\y_properties\y_properties_entry.inc(717) : error 010: invalid function or declaration
YSI_Visual\y_properties\y_properties_entry.inc(910) : warning 213: tag mismatch: expected tag "bool", but found none ("_")
YSI_Visual\y_properties\y_properties_entry.inc(910) : error 017: undefined symbol "GROUP_PROPERTY_BITS"
YSI_Visual\y_properties\y_properties_entry.inc(925) : warning 219: local variable "prop" shadows a variable at a preceding level
YSI_Visual\y_properties\y_properties_entry.inc(935) : warning 219: local variable "prop" shadows a variable at a preceding level
YSI_Visual\y_properties\y_properties_entry.inc(947) : warning 213: tag mismatch: expected tag "bool", but found none ("_")
YSI_Visual\y_properties\y_properties_entry.inc(947) : warning 202: number of arguments does not match definition
YSI_Visual\y_properties\y_properties_entry.inc(1007) : warning 200: symbol "@yH_OnPlayerLeaveCheckpointEx@0" is truncated to 31 characters
YSI_Visual\y_properties\y_properties_entry.inc(1007) : warning 200: symbol "@yH_OnPlayerLeaveCheckpointEx@0" is truncated to 31 characters
YSI_Visual\y_properties\y_properties_entry.inc(1011) : error 017: undefined symbol "NO_CHECKPOINT"
YSI_Visual\y_properties\y_properties_entry.inc(1020) : warning 213: tag mismatch: expected tag "bool", but found none ("_")
YSI_Visual\y_properties\y_properties_entry.inc(1020) : warning 202: number of arguments does not match definition
YSI_Visual\y_properties\y_properties_entry.inc(2001) : warning 235: public function lacks forward declaration (symbol "Property_ResetRebuy")
YSI_Visual\y_properties\y_properties_entry.inc(2001) : warning 219: local variable "prop" shadows a variable at a preceding level
YSI_Visual\y_properties\y_properties_entry.inc(2082) : warning 219: local variable "prop" shadows a variable at a preceding level
YSI_Visual\y_properties\y_properties_entry.inc(2118) : error 017: undefined symbol "Text_SendFormat"

* [y_distribute] fixed warning 214

YSI_Visual\y_areas\..\..\YSI_Core\y_master\y_distribute.inc(165) : warning 214: possibly a "const" array argument was intended: "masters"

* [y_groups] fixed warning 214

YSI_Players\y_groups\y_groups_impl.inc(382) : warning 214: possibly a "const" array argument was intended: "Iterator@gp"
YSI_Players\y_groups\y_groups_impl.inc(745) : warning 214: possibly a "const" array argument was intended: "gs"
YSI_Players\y_groups\y_groups_impl.inc(889) : warning 214: possibly a "const" array argument was intended: "n"
YSI_Players\y_groups\y_groups_impl.inc(947) : warning 214: possibly a "const" array argument was intended: "name"
YSI_Players\y_groups\y_groups__funcs.inc(562) : warning 214: possibly a "const" array argument was intended: "a"
YSI_Players\y_groups\y_groups__funcs.inc(607) : warning 214: possibly a "const" array argument was intended: "r"
YSI_Players\y_groups\y_groups__funcs.inc(607) : warning 214: possibly a "const" array argument was intended: "c"
YSI_Players\y_groups\y_groups__funcs.inc(607) : warning 214: possibly a "const" array argument was intended: "p"

* [y_commands] fixed warning 214

YSI_Visual\y_commands\y_commands_impl.inc(363) : warning 214: possibly a "const" array argument was intended: "function"
YSI_Visual\y_commands\y_commands_impl.inc(379) : warning 214: possibly a "const" array argument was intended: "cmd"
YSI_Visual\y_commands\y_commands_impl.inc(647) : warning 214: possibly a "const" array argument was intended: "func"
YSI_Visual\y_commands\y_commands_impl.inc(685) : warning 214: possibly a "const" array argument was intended: "f"
YSI_Visual\y_commands\y_commands_impl.inc(700) : warning 214: possibly a "const" array argument was intended: "cmd"
YSI_Visual\y_commands\y_commands_impl.inc(723) : warning 214: possibly a "const" array argument was intended: "command"
YSI_Visual\y_commands\y_commands_impl.inc(875) : warning 214: possibly a "const" array argument was intended: "altname"
YSI_Visual\y_commands\y_commands_impl.inc(875) : warning 214: possibly a "const" array argument was intended: "function"
YSI_Visual\y_commands\y_commands_impl.inc(915) : warning 214: possibly a "const" array argument was intended: "func"
YSI_Visual\y_commands\y_commands_impl.inc(1049) : warning 214: possibly a "const" array argument was intended: "func"

* Removed #pragma unused

Commenting out line 13 will give error about re-definition.

* Removed #if !defined YSI_gLockData

* `__COMPILER_sNAMEMAX` (try determine the maximum compiler symbol length).

* Disable warning 238 again (somehow vanished).